services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
    environment:
      - APP_ENV=local
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=laravel
      - DB_USERNAME=laravel
      - DB_PASSWORD=secret
    depends_on:
      - mysql
    ports:
      - "9000:9000"

  nginx:
    image: nginx:1.25
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./:/var/www
    depends_on:
      - php

  mysql:
    image: mysql:8.0
    container_name: jsonapi-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "8306:3306"
    volumes:
      - ./database/mysql:/var/lib/mysql
    command: >
      --default-authentication-plugin=mysql_native_password 
      --general-log=1 
      --general-log-file=/var/log/mysql/query.log

volumes:
  database_mysql:
